export type Product = {
  slug: string;
  article: string;
  name: string;
  range: string;
  group: string;
  application: string;
  summary: string;
  image: string;
  images?: string[];
  sourceUrl: string;
  badges: string[];
  highlights: string[];
  specs: Record<string, string>;
};

export const productRanges = [
  "Hydrogen",
  "SF6",
  "Alternative arc quenching and insulating gases",
  "Accessories",
];

export const productGroups = [
  "H2 Sensors",
  "H2 Leakage monitoring",
  "H2 Gas analyzers",
  "H2 Process Monitoring",
  "H2 Gas drying",
  "H2 Gas purification",
  "H2 gas generation",
  "H2 energy storage",
  "SF6 Leakage Detector",
  "SF6 Gas analyzer",
  "SF6 Service carts",
  "coupling",
  "SF6 Gas Density",
  "SF6 Gas System",
];

const h2Url = (slug: string) => `https://h2gassolution.com/products/${slug}`;

const h2GasSolutionProducts: Product[] = [
  {
    slug: "hydrogen-purity-sensor-tcm101-h2",
    article: "TCM101-H2",
    name: "TCM101-H2 Hydrogen Purity Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Compact hydrogen sensing",
    summary:
      "Compact hydrogen concentration sensing for hydrogen leak monitoring, integrated equipment, and industrial hydrogen applications.",
    image: "https://h2gassolution.com/products/tcm101-h2/tcm101-h2-1.jpg",
    sourceUrl: h2Url("hydrogen-purity-sensor-tcm101-h2"),
    badges: ["Sensor", "Thermal conductivity", "Fast response"],
    highlights: [
      "No reference gas required for compact hydrogen measurement",
      "MEMS thermal conductivity design for embedded equipment integration",
      "Fast response for leak monitoring and concentration change tracking",
    ],
    specs: {
      Model: "TCM101-H2",
      Gas: "Hydrogen gas (H2)",
      Type: "Compact hydrogen concentration and leak monitoring sensor",
      Principle: "Thermal conductivity",
      "Sampling method": "Diffusion type",
      "Detection range": "(0.2 to 4) %Vol; (0.2 to 10) %Vol",
      Accuracy: "Plus or minus 5% F.S",
      Repeatability: "Less than 2%",
      Resolution: "0.01 %Vol",
      "Preheat time": "Less than 10 seconds",
      "Response time": "Less than 3 seconds",
      "Working voltage": "12 VDC, optional 24 VDC",
      "Power consumption": "Less than 1 W",
    },
  },
  {
    slug: "micro-hydrogen-concentration-detector-tcm200",
    article: "TCM200",
    name: "TCM200 Micro Hydrogen Concentration Detector",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Embedded hydrogen detection",
    summary:
      "Compact hydrogen concentration detection for embedded equipment and flexible industrial integration.",
    image: "https://h2gassolution.com/products/tcm200/tcm200-1.jpg",
    sourceUrl: h2Url("micro-hydrogen-concentration-detector-tcm200"),
    badges: ["Micro detector", "IP67", "Selectable output"],
    highlights: [
      "Compact detector module for embedded hydrogen equipment",
      "Multiple output options for instrumentation integration",
      "Wide operating temperature and IP67 protection rating",
    ],
    specs: {
      Model: "TCM200",
      Gas: "Hydrogen gas (H2)",
      Type: "Compact hydrogen concentration detector",
      Principle: "Thermal conductivity",
      "Sampling method": "Diffusion type",
      "Detection range": "0.2 to 4 %Vol; 0.2 to 10 %Vol",
      "Measurement error": "Plus or minus 5% F.S",
      Repeatability: "Less than 2%",
      Resolution: "0.01 %Vol",
      "Preheat time": "Less than 10 s",
      "Response time": "Less than 3 s (T90)",
      "Working voltage": "12 VDC (9 to 16 VDC); 24 VDC (9 to 32 VDC)",
      Output: "4 to 20 mA, 0 to 5 V, RS-485, or CAN",
      Temperature: "-40 to +85 C operating; -40 to +105 C storage",
      "Pressure compensation": "50 to 150 kPa",
      Protection: "IP67",
      "Service life": "5 to 10 years",
      Size: "82.6 mm x 90.58 mm x 25.9 mm",
      Weight: "70 g",
    },
  },
  {
    slug: "industrial-hydrogen-concentration-sensor-pdm300",
    article: "PDM300",
    name: "PDM300 Industrial Hydrogen Concentration Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Industrial online sensing",
    summary:
      "Industrial online hydrogen concentration sensing for harsh environments and continuous process monitoring.",
    image: "https://h2gassolution.com/products/pdm300/pdm300-1.jpg",
    sourceUrl: h2Url("industrial-hydrogen-concentration-sensor-pdm300"),
    badges: ["Industrial", "Pipeline", "Palladium alloy"],
    highlights: [
      "Pipeline type sensor for continuous hydrogen concentration monitoring",
      "Palladium alloy thin-film principle for industrial applications",
      "RS-485 or 4 to 20 mA output for process integration",
    ],
    specs: {
      Model: "PDM300",
      Gas: "Hydrogen gas (H2)",
      Type: "Industrial online hydrogen concentration sensor",
      Principle: "Palladium alloy thin-film",
      Range: "0 to 20 %Vol, customizable",
      "Measurement error": "Plus or minus 2% F.S",
      Repeatability: "Less than 2%",
      "Preheat time": "Less than 5 s",
      "Sampling method": "Pipeline type",
      "Working voltage": "12 VDC",
      Output: "RS-485 or 4 to 20 mA",
      Temperature: "-40 to 70 C operating; -40 to 105 C storage",
      "Service life": "10 years",
      "Response time": "Less than 30 s",
      Dimensions: "142 mm x 43 mm x 43 mm",
      Weight: "165 g",
    },
  },
  {
    slug: "fuel-cell-hydrogen-sensor-fc-h2",
    article: "FC-H2",
    name: "FC-H2 Fuel Cell Hydrogen Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Low-concentration hydrogen safety",
    summary:
      "Low-concentration hydrogen sensing for fuel cell systems, compact safety modules, and embedded equipment monitoring.",
    image: "https://h2gassolution.com/products/fc-h2/fc-h2-1.jpg",
    sourceUrl: h2Url("fuel-cell-hydrogen-sensor-fc-h2"),
    badges: ["Fuel cell", "ppm", "Low concentration"],
    highlights: [
      "Low ppm hydrogen sensing for fuel cell safety applications",
      "Micro fuel cell principle with linear output behavior",
      "Compact 3 g component for embedded monitoring modules",
    ],
    specs: {
      Model: "FC-H2",
      Gas: "Hydrogen gas (H2)",
      Principle: "Micro fuel cell",
      Range: "0 to 1000 ppm",
      "Maximum overload": "2000 ppm",
      Sensitivity: "0.4 plus or minus 0.2 nA/ppm",
      "Response time": "Less than 60 s",
      Accuracy: "Plus or minus 3% F.S",
      "Lower detection limit": "1 ppm",
      Repeatability: "3%",
      Temperature: "-40 to 70 C",
      Humidity: "10 to 90% RH, non-condensing",
      "Service life": "6 years under normal use",
      Warranty: "12 months",
      Weight: "3 g",
    },
  },
  {
    slug: "portable-hydrogen-leak-detector-na-1",
    article: "NA-1",
    name: "NA-1 Portable Hydrogen Leak Detector",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Portable leak inspection",
    summary:
      "Portable hydrogen leak detection with dual-sensor, dual-range measurement for maintenance inspection and industrial hydrogen safety applications.",
    image: "https://h2gassolution.com/products/na-1/na-1-1.jpg",
    sourceUrl: h2Url("portable-hydrogen-leak-detector-na-1"),
    badges: ["Portable", "Dual range", "Explosion-proof"],
    highlights: [
      "Dual-sensor detection with automatic range switching",
      "Pump suction measurement for maintenance inspection workflows",
      "Audible and visual alarms for field safety response",
    ],
    specs: {
      Model: "NA-1",
      Gas: "Hydrogen gas (H2)",
      Type: "Portable handheld hydrogen leak detector",
      "Detection range": "(0 to 1000) ppm; (0.1 to 4) %Vol",
      Method: "Pump suction, 200 ml/min",
      "Preheat time": "Less than 60 seconds",
      "Response time": "Less than 2 seconds",
      Resolution: "1 ppm",
      Accuracy: "30% for ppm range; plus or minus 5% F.S for %Vol range",
      Alarm: "Audible and visual alarm with LED threshold indication",
      Battery: "Lithium battery, 3.6 to 4.2 V, up to 6 hours",
      Charger: "100 to 240 VAC input; 5.0 V 400 mA output",
      "Explosion-proof mark": "Ex ib IIC T3 Gb",
      Area: "Zone 1 and Zone 2",
      Dimensions: "169 mm x 60 mm x 28 mm",
      Weight: "400 g",
    },
  },
  {
    slug: "portable-hydrogen-leak-detector-na-8",
    article: "NA-8",
    name: "NA-8 Hydrogen Gas Detection Alarm Instrument",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "High-position leak inspection",
    summary:
      "Portable hydrogen detection and alarm support for elevated leak inspection, hard-to-reach hydrogen systems, and industrial safety applications.",
    image: "https://h2gassolution.com/products/na-8/na-8-1.jpg",
    sourceUrl: h2Url("portable-hydrogen-leak-detector-na-8"),
    badges: ["High-position", "6 m probe", "%LEL"],
    highlights: [
      "Telescopic probe supports elevated hydrogen leak inspection",
      "Designed for joints, flanges, coolers, dryers, and fans",
      "OLED display and touch keys for field operation",
    ],
    specs: {
      Model: "NA-8",
      Gas: "Hydrogen gas (H2)",
      Type: "Portable high-position hydrogen gas detector and alarm instrument",
      "Detection range": "(0 to 100) %LEL",
      "Alarm range": "Low: 10 to 25 %LEL; High: 25 to 80 %LEL",
      Method: "Diffusion type",
      Principle: "Catalytic combustion",
      "Response time": "Less than 30 seconds",
      Accuracy: "Less than or equal to plus or minus 5% F.S",
      Display: "OLED self-luminous display",
      Temperature: "-20 to 55 C working; 0 to 40 C storage",
      Humidity: "0 to 95 %RH, non-condensing",
      Probe: "Telescopic rod, 6 m",
      Reach: "Up to 8 m during handheld inspection",
      Weight: "Less than 1 kg",
    },
  },
  {
    slug: "fixed-hydrogen-leak-monitoring-system-na1000ms",
    article: "NA1000MS",
    name: "NA1000MS Fixed Hydrogen Leak Monitoring System",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Fixed multi-point safety monitoring",
    summary:
      "Fixed hydrogen leak monitoring for continuous online safety coverage, multi-point monitoring, and alarm control support.",
    image: "https://h2gassolution.com/products/na1000ms/na1000ms-1.jpg",
    sourceUrl: h2Url("fixed-hydrogen-leak-monitoring-system-na1000ms"),
    badges: ["Fixed", "1-16 channels", "Alarm records"],
    highlights: [
      "Centralized fixed hydrogen monitoring for generator and hydrogen operating points",
      "Controller supports multi-channel 4 to 20 mA transmitters",
      "Alarm records, branch alarms, general alarm, and DCS-friendly outputs",
    ],
    specs: {
      Model: "NA1000MS",
      Composition: "NA1000MR controller and NA1000DII hydrogen transmitter",
      Type: "Fixed multi-channel hydrogen leak monitoring and alarm system",
      Display: "TFT256 color LCD",
      Input: "1 to 8 two-wire channels, 4 to 20 mA transmitters, up to 16 channels",
      Output: "1 to 8 channels of 4 to 20 mA current output, up to 16 channels",
      Alarm: "1 to 16 branch alarms and 1 general alarm",
      "Alarm storage": "8000 alarm records",
      "Controller voltage": "210 to 230 VAC, 50/60 Hz",
      Installation: "Wall-mounted",
      "Controller dimensions": "440 mm x 330 mm x 130 mm",
      "Controller weight": "9.5 kg",
      "Transmitter range": "0 to 4 %, 0 to 100 %LEL",
      "Transmitter accuracy": "Plus or minus 2% F.S",
      "Sampling method": "Natural diffusion",
      Environment: "-10 to 50 C, 0 to 98 %RH",
      "Explosion-proof rating": "Ex ia IIC T4 Ga",
    },
  },
  {
    slug: "online-hydrogen-leak-monitoring-system-na1000ja",
    article: "NA1000JA",
    name: "NA1000JA Online Hydrogen Leak Monitoring System",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Cooling-water hydrogen leak monitoring",
    summary:
      "Online hydrogen leakage monitoring for generator cooling-water applications, leak-volume tracking, and hydrogen removal support.",
    image: "https://h2gassolution.com/products/na1000ja/na1000ja-1.jpg",
    sourceUrl: h2Url("online-hydrogen-leak-monitoring-system-na1000ja"),
    badges: ["Online", "Leak volume", "RS-485"],
    highlights: [
      "Monitors hydrogen concentration, daily leak volume, and exhaust volume",
      "Designed for inner cooling water tank hydrogen applications",
      "Supports real-time display, storage, query, and DCS upload",
    ],
    specs: {
      Model: "NA1000JA",
      Type: "Online hydrogen leak volume and concentration monitoring system",
      "Working voltage": "12 VDC",
      "Inlet pressure": "0.4 to 0.6 MPa",
      "Nitrogen generation flow": "0.5 to 1 L/min",
      Output: "RS-485",
      Environment: "-10 to +50 C, 0 to 85 %RH",
      Dimensions: "505 mm x 320 mm x 130 mm",
      Weight: "15 kg",
      "Hydrogen concentration": "Up to 20 %",
      "Concentration alarm": "2 % and 10 %",
      "Leak volume alarm": "0.3 m3/day and 5 m3/day",
      "Data functions": "Real-time display, storage, query, and DCS upload",
    },
  },
  {
    slug: "portable-hydrogen-analyzer-ra601h-ii",
    article: "RA601H-II",
    name: "RA601H-II Portable Hydrogen Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Portable hydrogen quality analysis",
    summary:
      "Portable hydrogen analysis for hydrogen purity, humidity, oxygen content, and gas replacement checks in field workflows.",
    image: "https://h2gassolution.com/products/ra601h-ii/ra601h-ii-1.jpg",
    sourceUrl: h2Url("portable-hydrogen-analyzer-ra601h-ii"),
    badges: ["Portable", "Multi-parameter", "Battery"],
    highlights: [
      "Portable purity, humidity, and oxygen analysis for field workflows",
      "Supports hydrogen replacement stage checks with optional gases",
      "Built-in lithium battery supports more than 8 hours of operation",
    ],
    specs: {
      Model: "RA601H-II",
      Type: "Portable multi-parameter hydrogen analyzer",
      "Purity principle": "Micro thermal conductivity",
      "Purity range": "H2/Air 90 to 100%; CO2/H2 0 to 100%; CO2/Air 0 to 100%",
      "Purity uncertainty": "Plus or minus 2% F.S",
      "Purity response": "Less than or equal to 15 seconds",
      "Humidity principle": "Resistive-capacitive",
      "Humidity range": "-80 to 20 C",
      "Humidity uncertainty": "2 C",
      "Oxygen principle": "Electrochemical",
      "Oxygen range": "0 to 25 %",
      "Oxygen uncertainty": "Plus or minus 1% F.S",
      "Oxygen response": "Less than or equal to 20 seconds",
      Power: "AC/DC dual use, built-in 6000 mAh lithium battery",
      Dimensions: "242 mm x 282 mm x 104 mm",
      Weight: "4 kg",
      "Optional gases": "CO2, N2, Ar, and others",
    },
  },
  {
    slug: "hydrogen-purity-analyzer-7866-7872d",
    article: "7866+7872D",
    name: "7866+7872D Hydrogen Purity Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Generator hydrogen purity analysis",
    summary:
      "Online hydrogen purity analysis for generator hydrogen cooling systems and gas replacement monitoring in power plant applications.",
    image: "https://h2gassolution.com/products/7866-7872d/7866-7872d-1.jpg",
    sourceUrl: h2Url("hydrogen-purity-analyzer-7866-7872d"),
    badges: ["Online", "Sampling system", "Explosion-proof"],
    highlights: [
      "Online hydrogen purity analyzer with sampling system",
      "Covers CO2 in air, H2 in CO2, and H2 in air measurement stages",
      "Suitable for generator hydrogen cooling and gas replacement monitoring",
    ],
    specs: {
      Model: "7866+7872D",
      Type: "Online hydrogen purity analyzer with sampling system",
      "Measurement range": "0 to 100 % CO2 in air; 0 to 100 % H2 in CO2; 75 to 100 % H2 in air",
      Accuracy: "Plus or minus 2% F.S under standard conditions",
      "H2 response time": "63%: 13 s; 90%: 23 s",
      "CO2 response time": "63%: 24 s; 90%: 45 s",
      Output: "4 to 20 mA, factory setting 75 to 100 % H2 in air",
      "Maximum load": "800 ohm",
      "Sample gas flow": "0.5 SCFH",
      "Explosion-proof rating": "Ex d IIC T6",
      Dimensions: "800 mm x 400 mm x 1660 mm",
      Weight: "131 kg",
    },
  },
  {
    slug: "oxygen-in-hydrogen-analyzer-ra1630b",
    article: "RA1630B",
    name: "RA1630B Oxygen in Hydrogen Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Oxygen-in-hydrogen safety analysis",
    summary:
      "Real-time oxygen-in-hydrogen analysis for hydrogen-cooled generator systems and power industry safety monitoring.",
    image: "https://h2gassolution.com/products/ra1630b/ra1630b-1.jpg",
    sourceUrl: h2Url("oxygen-in-hydrogen-analyzer-ra1630b"),
    badges: ["Oxygen", "Fixed", "4-20 mA"],
    highlights: [
      "Fixed oxygen-in-hydrogen analyzer for safety monitoring",
      "Programmable alarm outputs for process supervision",
      "Supports 24 VDC or 220 VAC installation requirements",
    ],
    specs: {
      Model: "RA1630B",
      Type: "Fixed oxygen in hydrogen analyzer",
      Range: "0 to 2 % O2",
      Accuracy: "Plus or minus 0.03%",
      Repeatability: "Plus or minus 0.01%",
      "Response time": "20 s",
      Output: "4 to 20 mA, maximum load 800 ohm",
      Power: "24 VDC or 220 VAC",
      Alarm: "DC 24V 1A, two independently programmable alarm outputs",
      "Explosion-proof rating": "Ex ia IIC T4 Ga",
    },
  },
  {
    slug: "online-oxygen-in-hydrogen-analyzer-ra1630",
    article: "RA1630",
    name: "RA1630 Online Oxygen in Hydrogen Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Online oxygen monitoring",
    summary:
      "Fixed online oxygen-in-hydrogen analysis for hydrogen quality monitoring and safer industrial hydrogen operation.",
    image: "https://h2gassolution.com/products/ra1630/ra1630-1.jpg",
    sourceUrl: h2Url("online-oxygen-in-hydrogen-analyzer-ra1630"),
    badges: ["Online", "Oxygen", "Fixed analyzer"],
    highlights: [
      "Continuous oxygen-in-hydrogen analysis in fixed hydrogen systems",
      "Supports hydrogen quality and process safety monitoring",
      "Useful for online industrial hydrogen instrumentation panels",
    ],
    specs: {
      Model: "RA1630",
      Type: "Fixed online oxygen in hydrogen analyzer",
      Parameter: "Oxygen content in hydrogen",
      Installation: "Online fixed analyzer",
      Range: "Available on request",
      Accuracy: "Available on request",
      Outputs: "Available on request",
      "Power supply": "Available on request",
      "Explosion-proof rating": "Available on request",
    },
  },
  {
    slug: "online-precision-dew-point-meter-ra242j",
    article: "RA242J",
    name: "RA242J Online Precision Dew Point Meter",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Hydrogen moisture control",
    summary:
      "Fixed online dew point and moisture monitoring for hydrogen quality control and industrial gas process support.",
    image: "https://h2gassolution.com/products/ra242j/ra242j-1.jpg",
    sourceUrl: h2Url("online-precision-dew-point-meter-ra242j"),
    badges: ["Dew point", "Online", "Moisture"],
    highlights: [
      "Continuous dew point monitoring in hydrogen and process gas systems",
      "Supports hydrogen moisture condition control",
      "Fixed analyzer format for plant instrumentation panels",
    ],
    specs: {
      Model: "RA242J",
      Type: "Fixed online dew point meter",
      Parameter: "Dew point / moisture condition",
      Installation: "Online fixed analyzer",
      Range: "Available on request",
      Accuracy: "Available on request",
      Outputs: "Available on request",
      "Power supply": "Available on request",
      "Explosion-proof rating": "Available on request",
    },
  },
  {
    slug: "hydrogen-purity-analyzer-rs-301on",
    article: "RS-301ON",
    name: "RS-301ON Hydrogen Purity Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Fixed hydrogen purity analysis",
    summary:
      "Fixed hydrogen purity analysis for hydrogen-cooled generator units with sampling, temperature compensation, and long-term stable monitoring.",
    image: "https://h2gassolution.com/products/rs-301on/rs-301on-1.jpg",
    sourceUrl: h2Url("hydrogen-purity-analyzer-rs-301on"),
    badges: ["Fixed", "Purity", "Generator"],
    highlights: [
      "Fixed analyzer for hydrogen-cooled generator purity monitoring",
      "Covers CO2 and H2 gas replacement measurement ranges",
      "Explosion-proof design for industrial hydrogen environments",
    ],
    specs: {
      Model: "RS-301ON",
      Type: "Fixed hydrogen purity analyzer",
      "Measurement range": "CO2 in air 0 to 100%; CO2 in H2 0 to 100%; H2 in air 90 to 100%",
      Accuracy: "Plus or minus 2% F.S",
      Output: "4 to 20 mA, factory setting H2 in air 90 to 100%",
      "Maximum load": "800 ohm",
      "Alarm relay": "Contact current 3 A",
      "Sample gas flow": "0.5 SCFH",
      "Sampling pressure": "Less than or equal to 0.1 MPa",
      Power: "AC 90 to 265 V, 50 Hz, 35 W",
      "Explosion-proof rating": "Ex d IIC T6 Gb",
      Dimensions: "800 mm x 400 mm x 1660 mm",
      Weight: "130 kg",
    },
  },
  {
    slug: "hydrogen-quality-analyzer-rs301on-iii",
    article: "RS301ON-III",
    name: "RS301ON-III Hydrogen Quality Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Integrated hydrogen quality analysis",
    summary:
      "Integrated online hydrogen quality analysis for purity, humidity, oxygen content, and residual hydrogen monitoring in generator hydrogen systems.",
    image: "https://h2gassolution.com/products/rs301on-iii/rs301on-iii-1.jpg",
    sourceUrl: h2Url("hydrogen-quality-analyzer-rs301on-iii"),
    badges: ["Integrated", "Purity", "Humidity + oxygen"],
    highlights: [
      "Integrated analysis of purity, humidity, oxygen, and residual hydrogen",
      "Built for generator hydrogen system quality monitoring",
      "Combines multiple explosion-proof analyzer modules",
    ],
    specs: {
      Model: "RS301ON-III",
      Type: "Integrated online hydrogen quality analyzer",
      "Purity principle": "Micro thermal conductivity",
      "Purity range": "H2/Air 90 to 100%; CO2/H2 0 to 100%; CO2/Air 0 to 100%",
      "Purity error": "Plus or minus 2% F.S",
      "Humidity principle": "Resistive-capacitive",
      "Humidity range": "-80 to 20 C",
      "Humidity error": "Plus or minus 2 C",
      "Oxygen principle": "Electrochemical",
      "Oxygen range": "0 to 25 %",
      "Oxygen error": "Plus or minus 1% F.S",
      "Residual hydrogen principle": "Catalytic combustion",
      "Residual hydrogen range": "0 to 4 %Vol",
      "Residual hydrogen error": "Plus or minus 1% F.S",
      "Explosion-proof": "Ex d IIB + H2 T5 Gb / Ex d IIC T6 Gb",
    },
  },
  {
    slug: "online-hydrogen-purity-analyzer-rs301on",
    article: "RS301ON",
    name: "RS301ON Online Hydrogen Purity Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Online hydrogen purity monitoring",
    summary:
      "Fixed online hydrogen purity analysis for hydrogen quality monitoring and continuous industrial hydrogen process support.",
    image: "https://h2gassolution.com/products/rs301on/rs301on-1.jpg",
    sourceUrl: h2Url("online-hydrogen-purity-analyzer-rs301on"),
    badges: ["Online", "Purity", "Fixed analyzer"],
    highlights: [
      "Continuous fixed hydrogen purity monitoring in industrial systems",
      "Online analyzer format for process instrumentation",
      "Suitable for hydrogen quality supervision and plant monitoring points",
    ],
    specs: {
      Model: "RS301ON",
      Type: "Fixed online hydrogen purity analyzer",
      Parameter: "Hydrogen purity",
      Installation: "Online fixed analyzer",
      Range: "Available on request",
      Accuracy: "Available on request",
      Outputs: "Available on request",
      "Power supply": "Available on request",
      "Explosion-proof rating": "Available on request",
    },
  },
  {
    slug: "integrated-hydrogen-control-unit-jcqk",
    article: "JCQK",
    name: "JCQK Integrated Hydrogen Control Unit",
    range: "Hydrogen",
    group: "H2 Process Monitoring",
    application: "Generator hydrogen process control",
    summary:
      "Integrated process control for generator hydrogen replacement, hydrogen filling, replenishment, discharge, and online hydrogen parameter monitoring.",
    image: "https://h2gassolution.com/products/jcqk/jcqk-1.jpg",
    sourceUrl: h2Url("integrated-hydrogen-control-unit-jcqk"),
    badges: ["Process control", "Filling", "Monitoring"],
    highlights: [
      "Integrated hydrogen replacement, filling, replenishment, and discharge control",
      "Supports online hydrogen parameter monitoring",
      "Designed for generator hydrogen system process workflows",
    ],
    specs: {
      Model: "JCQK",
      Type: "Integrated hydrogen process control and monitoring unit",
      "Design pressure": "1.0 MPa",
      "Inlet pressure": "0.6 to 1 MPa",
      "Outlet pressure": "0.3 to 0.6 MPa",
      "Power supply": "220 VAC",
      Output: "4 to 20 mA and switching signals",
      Weight: "600 kg",
    },
  },
  {
    slug: "hydrogen-dryer-rh-aqg-iii",
    article: "RH-AQG-III",
    name: "RH-AQG-III Hydrogen Dryer",
    range: "Hydrogen",
    group: "H2 Gas drying",
    application: "Generator hydrogen drying",
    summary:
      "Third-generation hydrogen drying and humidity control for generator hydrogen systems, with purification support and three-tower adsorption design.",
    image: "https://h2gassolution.com/products/rh-aqg-iii/rh-aqg-iii-1.jpg",
    sourceUrl: h2Url("hydrogen-dryer-rh-aqg-iii"),
    badges: ["Drying", "Dew point", "100 m3/h"],
    highlights: [
      "Hydrogen drying and humidity control for generator hydrogen systems",
      "Supports gas dew point measurement and automatic drainage",
      "Electrical parts meet IIC T4 explosion-proof grade",
    ],
    specs: {
      Model: "RH-AQG-III",
      Type: "Hydrogen drying and humidity control system",
      Capacity: "100 m3/h (NPT)",
      "Inlet/outlet dew point": "10 / -30 to -15 C",
      "Cooling water pressure": "200 to 1000 kPa",
      "Cooling water temperature": "Less than or equal to 38 C",
      "Dew point range": "-40 to +100 C",
      Output: "4 to 20 mA",
      Flange: "DN40",
      "Drain trap": "Automatic drainage",
      "Compressed air": "0.5 to 0.8 MPa",
      "Explosion-proof rating": "Electrical parts meet IIC T4 explosion-proof grade",
      Power: "380 VAC, 50 Hz",
      "Rated power": "14 kW",
    },
  },
  {
    slug: "hydrogen-purification-compensation-unit-rlhj68-1",
    article: "RLHJ68-1",
    name: "RLHJ68-1 Hydrogen Purification Compensation Unit",
    range: "Hydrogen",
    group: "H2 Gas purification",
    application: "Hydrogen replenishment and pressure maintenance",
    summary:
      "Automatic hydrogen generation and replenishment for generator hydrogen pressure maintenance, with purification and safety monitoring support.",
    image: "https://h2gassolution.com/products/rlhj68-1/rlhj68-1-1.jpg",
    sourceUrl: h2Url("hydrogen-purification-compensation-unit-rlhj68-1"),
    badges: ["Purification", "Compensation", "99.99% purity"],
    highlights: [
      "Automatic hydrogen generation and compensation for pressure maintenance",
      "Hydrogen purity above 99.99% for generator support",
      "Open-frame water-cooled system for industrial hydrogen rooms",
    ],
    specs: {
      Model: "RLHJ68-1",
      Type: "Automatic hydrogen generation and compensation unit",
      "Input voltage": "380 VAC",
      "Hydrogen generation flow": "1 to 2 Nm3/h",
      "Hydrogen purity": "More than 99.99%",
      "Hydrogen supply pressure": "Adjusted according to on-site rated hydrogen requirements",
      Cooling: "Water cooling",
      "Cooling water temperature": "Less than or equal to 15 C",
      Environment: "Normal temperature and normal pressure conditions",
      Form: "Open frame",
    },
  },
  {
    slug: "hydrogen-purification-unit-rlhj68",
    article: "RLHJ68",
    name: "RLHJ68 Hydrogen Purification Unit",
    range: "Hydrogen",
    group: "H2 Gas purification",
    application: "Generator hydrogen purification",
    summary:
      "Hydrogen purification for separating oxygen, nitrogen, and carbon dioxide impurities while improving hydrogen purity in generator hydrogen systems.",
    image: "https://h2gassolution.com/products/rlhj68/rlhj68-1.jpg",
    sourceUrl: h2Url("hydrogen-purification-unit-rlhj68"),
    badges: ["Purification", "60 m3/h", "Generator"],
    highlights: [
      "Separates oxygen, nitrogen, and carbon dioxide impurities",
      "Improves generator hydrogen purity to at least 99%",
      "Large cabinet system for generator hydrogen quality management",
    ],
    specs: {
      Model: "RLHJ68",
      Type: "Hydrogen purification and separation unit",
      "Feed gas flow": "60 m3/h",
      "Inlet pressure": "0.25 to 0.6 MPa",
      "Purity improvement": "At least 99%",
      "Power supply": "380 VAC",
      Power: "9 kW",
      Dimensions: "1870 mm x 1260 mm x 2165 mm",
      Weight: "1500 kg",
    },
  },
  {
    slug: "pem-water-electrolysis-hydrogen-generation-system",
    article: "PEM",
    name: "PEM Water Electrolysis Hydrogen Generation System",
    range: "Hydrogen",
    group: "H2 gas generation",
    application: "On-site hydrogen generation",
    summary:
      "Modular PEM hydrogen production for high-purity hydrogen output, fast renewable energy response, and scalable on-site clean hydrogen applications.",
    image:
      "https://h2gassolution.com/products/pem-water-electrolysis/pem-water-electrolysis-1.jpg",
    sourceUrl: h2Url("pem-water-electrolysis-hydrogen-generation-system"),
    badges: ["PEM", "99.999%", "0.5-200 Nm3/h"],
    highlights: [
      "Modular PEM hydrogen generation for on-site clean hydrogen supply",
      "High-purity output with hydrogen purification",
      "Wide operating range for renewable energy response and scalable capacity",
    ],
    specs: {
      Technology: "PEM water electrolysis hydrogen generation",
      "Hydrogen purity": "99.999%, with hydrogen purification",
      "Outlet pressure": "1.6 MPa or 3 MPa, 16 bar or 30 bar",
      "Operating range": "10 to 100%",
      "DC power consumption": "4.5 kWh/Nm3",
      "Capacity range": "0.5 to 200 Nm3/h",
    },
  },
  {
    slug: "hydrogen-electric-coupled-energy-storage-system-h2pem-b",
    article: "H2PEM-B",
    name: "H2PEM-B Hydrogen Electric Coupled Energy Storage System",
    range: "Hydrogen",
    group: "H2 energy storage",
    application: "Hydrogen power and long-cycle energy storage",
    summary:
      "Integrated hydrogen production, storage, and fuel cell power generation for long-cycle clean energy storage and containerized renewable energy applications.",
    image: "https://h2gassolution.com/products/h2pem-b/h2pem-b-1.jpg",
    sourceUrl: h2Url("hydrogen-electric-coupled-energy-storage-system-h2pem-b"),
    badges: ["Energy storage", "Containerized", "Fuel cell"],
    highlights: [
      "Combines hydrogen production, storage, and fuel cell generation",
      "Supports long-cycle clean energy storage applications",
      "Containerized 20-foot or 40-foot configurations",
    ],
    specs: {
      Model: "H2PEM-B",
      "Hydrogen purity": "99.999%",
      "Production pressure": "Less than 3 MPa, adjustable from 0 to 100%",
      "Water consumption": "11 L water per kilogram of hydrogen",
      "Source water": "Tap water",
      "Production power": "AC380V",
      "Power consumption": "Less than 4.5 kWh/Nm3",
      "Storage pressure": "Solid-state 3 MPa, or gas storage 35 MPa / 70 MPa",
      "Fuel cell generation": "15 kWh per kilogram of hydrogen, configurable",
      "Heating efficiency": "Heat-only 40 to 50%, total 80 to 90%",
      "Hot water temperature": "45 to 70 C",
      "Pipe material": "316L",
      Protection: "IP54",
      "Container size": "20-foot about 6.1 m, or 40-foot about 12.2 m",
    },
  },
];

export const products: Product[] = [
  ...h2GasSolutionProducts,
  {
    slug: "sf6-leak-detector",
    article: "PGAS-32",
    name: "SF6 Leak Detector",
    range: "SF6",
    group: "SF6 Leakage Detector",
    application: "Substation inspection",
    summary:
      "Portable SF6 leakage detection equipment for switchgear rooms, GIS maintenance, and field service teams.",
    image: "/pic/sf6-leak-detector.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-leak-detector/",
    badges: ["Portable", "ppm detection", "Field service"],
    highlights: [
      "Infrared principle for accurate SF6 leakage detection",
      "Built for routine inspections and emergency troubleshooting",
      "Compact handheld form for GIS and substation maintenance",
    ],
    specs: {
      Gas: "SF6",
      Method: "Infrared detection",
      Use: "Leak location and maintenance inspection",
    },
  },
  {
    slug: "sf6-room-monitor",
    article: "NA1000MR",
    name: "SF6 Room Monitor",
    range: "SF6",
    group: "SF6 Leakage Detector",
    application: "Indoor switchgear rooms",
    summary:
      "Fixed SF6 room monitoring system for continuous safety supervision in GIS rooms and power facilities.",
    image: "/pic/sf6-room-monitor.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-room-monitor/",
    badges: ["Fixed monitor", "Safety", "Continuous"],
    highlights: [
      "Continuous monitoring for SF6 gas leakage risk",
      "Suitable for indoor substations and GIS rooms",
      "Supports safety alarm workflows for operation teams",
    ],
    specs: {
      Installation: "Wall-mounted / fixed",
      Scenario: "GIS room and substation",
      Output: "Alarm and monitoring signal",
    },
  },
  {
    slug: "sf6-gas-analyzer",
    article: "RA912F",
    name: "SF6 Gas Analyzer",
    range: "SF6",
    group: "SF6 Gas analyzer",
    application: "Gas quality testing",
    summary:
      "SF6 gas analyzer for purity, moisture, and decomposition product checks during equipment maintenance.",
    image: "/pic/sf6-gas-analyzer.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-gas-analyzer/",
    badges: ["Analyzer", "Quality", "Maintenance"],
    highlights: [
      "Checks key SF6 gas quality indicators",
      "Designed for maintenance and commissioning workflows",
      "Supports decision-making before reuse, recovery, or regeneration",
    ],
    specs: {
      Parameters: "Purity / moisture / decomposition",
      Use: "SF6 quality analysis",
      Format: "Portable analyzer",
    },
  },
  {
    slug: "sf6-service-carts",
    article: "RFA / RF Series",
    name: "SF6 Service Carts",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Gas handling",
    summary:
      "SF6 handling units for recovery, evacuation, filling, purification, and gas storage operations.",
    image: "/pic/sf6-service-carts.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-service-carts/",
    badges: ["Recovery", "Filling", "Purification"],
    highlights: [
      "Complete SF6 gas handling for utility maintenance",
      "Covers recovery, evacuation, filling, and storage operations",
      "Available in compact, modular, and high-capacity configurations",
    ],
    specs: {
      Functions: "Recover / evacuate / fill / purify",
      Platform: "Mobile service cart",
      Gas: "SF6",
      "Recovery speed range": "4 to 30 m3/h by model",
      "Vacuum compressor": "3.6 to 30 m3/h by model",
      "Vacuum pump": "16 to 64 m3/h by model",
      Coupling: "DN8 / DN20 by model",
    },
  },
  {
    slug: "rfa-modular-sf6-gas-cart",
    article: "RFA",
    name: "RFA Modular SF6 Gas Cart",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Modular field service",
    summary:
      "Modular SF6 gas recovery cart for small gas compartments, flexible module combination, and field maintenance work.",
    image: "/pic/rfa-modular-sf6-gas-cart.webp",
    sourceUrl: "https://www.sf6relations.com/rfa-modular-sf6-gas-cart/",
    badges: ["Modular", "Mobile", "Service cart"],
    highlights: [
      "2 to 6 functional modules can be combined for different working conditions",
      "Oil-free compressor and oil-free vacuum compressor help avoid SF6 gas contamination",
      "Patented SF6 gas cooling system improves recovery efficiency",
      "Deep recovery down to 1 mbar for small gas compartments",
      "Compact module size supports easy transport and quick site assembly",
      "Quick self-locking couplings make connection fast and sealing reliable",
    ],
    specs: {
      Model: "RFA Mini Series",
      Type: "Modular SF6 gas recovery cart",
      Gas: "SF6",
      Operation: "Recovery / evacuation / refilling",
      Mobility: "Mobile",
      "Module combination": "2 to 6 functional modules",
      "Recommended gas quantity": "0 to 50 kg small SF6 gas compartments",
      "Oil-free compressor": "1 unit, 4 m3/h standard configuration",
      "Oil-free vacuum compressor": "1 unit, 7.2 m3/h, final vacuum < 1 mbar",
      "Vacuum pump": "1 unit, 16 m3/h, final vacuum < 10 Pa or < 100 Pa by configuration",
      "Recovery final vacuum": "< 1 mbar",
      "Gas cooling system": "1 patented SF6 gas cooling system",
      "Filtering device": "1 set for SF6 gas dehydration and impurity removal",
      "Main control panel": "1 unit",
      Wheels: "Each module has 2 fixed wheels and 2 universal wheels",
      "Connection hose": "5 m braided hose with DN20 / DN8 self-sealing couplings",
      "Cylinder hose": "3 m braided hose with DN8 self-sealing coupling / China cylinder connector",
      "Power cable": "10 m",
      Dimensions: "930 mm x 980 mm x 1000 mm",
      "Power supply": "AC 380 V, 50 Hz, three phase",
      Weight: "280 kg",
      Color: "Orange",
      "Optional RFA8": "2 x 4 m3/h compressors, 1 x 16 m3/h vacuum compressor, gas cooling system, main control panel",
      "Optional RFAV": "AC 220 V, 50 Hz, two phase power supply",
    },
  },
  {
    slug: "rf051-compact-sf6-gas-recovery",
    article: "RF-051",
    name: "RF051 Compact SF6 Gas Recovery",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Compact recovery",
    summary:
      "Compact SF6 recovery unit for evacuation, gas recovery, refilling, and cylinder pressurizing service.",
    image: "/pic/rf051-compact-sf6-gas-recovery.webp",
    sourceUrl: "https://www.sf6relations.com/rf051-compact-sf6-gas-recovery/",
    badges: ["Compact", "Recovery", "Portable"],
    highlights: [
      "12 standard configurations for different control, vacuum pump, and storage tank requirements",
      "Compact mobile design for substations, repair work, and limited-space field environments",
      "Manual, one-button, and touch screen control options available",
      "Molecular sieve filtering and drying removes moisture, decomposition products, and solid particles",
      "Oil-free recovery compressor supports clean and efficient SF6 gas recovery",
      "Safety valves and anti-oil-return protection reduce gas leakage and oil contamination risk",
    ],
    specs: {
      Model: "RF-051",
      Type: "Compact SF6 gas recovery unit",
      Gas: "SF6",
      Function: "Vacuum evacuation / gas recovery / refilling / cylinder pressurizing",
      Standard: "Designed and manufactured according to DL/T662",
      "Application range": "72.5 kV to 110 kV SF6 electrical equipment; 220 kV / 500 kV porcelain column circuit breakers",
      "Model options": "12 standard configurations",
      "Control modes": "Manual (H), one-button (K), touch screen (T)",
      "Vacuum pump options": "17 m3/h (B1) or 64 m3/h (B2)",
      "Storage tank options": "No tank (C1) or 70 L tank (C2)",
      "Oil-free water-cooled compressor": "15 m3/h",
      "Output final pressure": "50 bar",
      "Evacuation speed": "17 m3/h (B1) / 64 m3/h (B2)",
      "Final vacuum": "<= 10 Pa",
      "Annual leakage rate": "<= 0.5%",
      "Dust filtration accuracy": "< 1 um",
      "Regulated output pressure": "1 to 10 bar",
      Vaporizer: "1.5 kW",
      "Power supply": "AC 380 V, 50 Hz, three-phase five-wire",
      Power: "6 kW",
      Dimensions: "1490 mm x 1070 mm x 2030 mm",
      Weight: "Approx. 550 to 600 kg, depending on configuration",
      "Recovery hose": "DN19 x 10 m, DN20 self-sealing coupling on one end, ball valve and cylinder connector on the other end",
      "Refilling hose": "DN13 x 3 m, DN20 self-sealing coupling on one end, ball valve and cylinder connector on the other end",
      "Power cable": "10 m",
      "Auxiliary recovery cooling": "Water cooling",
    },
  },
  {
    slug: "sf6-gas-filling-cart",
    article: "RF-J Series",
    name: "SF6 Gas Filling Cart",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Gas filling",
    summary:
      "SF6 refilling and evacuating device for gas insulated switchgear maintenance and commissioning.",
    image: "/pic/sf6-gas-filling-cart.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-gas-filling-cart/",
    badges: ["Refilling", "Evacuating", "Switchgear"],
    highlights: [
      "Designed for SF6 filling and evacuation workflows",
      "Useful for switchgear maintenance and commissioning",
      "Supports controlled pressure handling in the field",
    ],
    specs: {
      Function: "Fill / evacuate",
      Equipment: "Gas insulated switchgear",
      Type: "Mobile filling cart",
      "Pressure units": "bar, psi and kPa",
      "Filling pressure": "Reduced to desired pressure by integrated pressure reducer",
      "Cylinder heating": "Cylinder heaters available by configuration",
    },
  },
  {
    slug: "rf151-mid-sf6-gas-handling",
    article: "RF-151",
    name: "RF151 MID SF6 Gas Handling",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Medium-capacity gas handling",
    summary:
      "Medium SF6 gas handling unit for vacuum evacuation, gas recovery, refilling, cylinder pressurizing, and vaporized gas output.",
    image: "/pic/rf151-mid-sf6-gas-handling.webp",
    sourceUrl: "https://www.sf6relations.com/rf151-mid-sf6-gas-handling/",
    badges: ["MID handling", "PLC control", "SF6 recovery"],
    highlights: [
      "10 standard configurations with control, vacuum compressor, vacuum pump, and tank options",
      "PLC control and touch screen operation make the process simple and clear",
      "Supports direct filling, regulated pressure output, gas-phase pressurizing, and liquid-phase pressurizing",
      "Oil-free recovery compressor and refrigeration liquefaction system improve recovery efficiency",
      "Molecular sieve filtering and drying removes moisture and decomposition products",
      "Suitable for 110 kV GIS, 220 kV GIS, and 500 kV porcelain column circuit breakers",
      "Compact semi-closed protective structure with integrated four-wheel movement",
    ],
    specs: {
      Model: "RF-151",
      Type: "MID SF6 gas handling unit",
      Gas: "SF6",
      Function: "Vacuum evacuation / recovery / refilling / cylinder pressurizing / vaporized output",
      Standard: "Designed and manufactured according to DL/T662",
      "Application range": "110 kV GIS, 220 kV GIS, 500 kV porcelain column circuit breakers",
      "Model options": "10 standard configurations",
      "Control modes": "One-button control (K) or touch screen control (T)",
      "Vacuum compressor options": "15 m3/h (A1) <= 5000 Pa; 20 m3/h (A2) <= 5 Pa",
      "Vacuum pump options": "17 m3/h (B1) or 64 m3/h (B2), final vacuum <= 10 Pa",
      "Storage tank options": "No tank / 120 L / 300 L / 600 L / 1000 L external tank",
      "Oil-free water-cooled compressor": "15 m3/h (A1) / 20 m3/h (A2)",
      "Oil-free booster": "5 m3/h for liquid SF6",
      "Output final pressure": "50 bar",
      "Evacuation speed": "17 m3/h (B1) / 64 m3/h (B2)",
      "Final vacuum": "<= 10 Pa",
      "Tank design pressure": "50 bar",
      "Annual leakage rate": "<= 0.5%",
      "Dust filtration accuracy": "< 1 um",
      "Regulated output pressure": "1 to 10 bar",
      Vaporizer: "1.5 kW",
      "Power supply": "AC 380 V, 50 Hz, three-phase five-wire",
      Power: "17 kW",
      Dimensions: "2850 mm x 1500 mm x 1760 mm",
      Structure: "Semi-closed protective structure, integrated four-wheel mobile design",
      "Recovery hose": "DN19 x 10 m, DN20 self-sealing coupling on one end, ball valve and cylinder connector on the other end",
      "Refilling hose": "DN13 x 3 m, DN20 self-sealing coupling on one end, ball valve and cylinder connector on the other end",
      "Power cable": "10 m",
      "Auxiliary recovery cooling": "Water cooling",
    },
  },
  {
    slug: "rf151m-mixed-gas-recovery-separation",
    article: "RF-151M",
    name: "RF151M Mixed Gas Recovery Separation Unit",
    range: "Alternative arc quenching and insulating gases",
    group: "SF6 Service carts",
    application: "SF6/N2 mixed gas separation",
    summary:
      "Recovery and separation unit for SF6/N2 mixed insulating gas, designed for online separation and SF6 reuse.",
    image: "/pic/rf151m-mixed-gas-recovery-separation-1.webp",
    images: [
      "/pic/rf151m-mixed-gas-recovery-separation-1.webp",
      "/pic/rf151m-mixed-gas-recovery-separation-2.webp",
      "/pic/rf151m-mixed-gas-recovery-separation-3.webp",
      "/pic/rf151m-mixed-gas-recovery-separation-4.webp",
    ],
    sourceUrl: "https://www.sf6relations.com/rf151m-mixed-gas-recovery-separation/",
    badges: ["Mixed gas", "Membrane separation", "SF6 reuse"],
    highlights: [
      "Designed for SF6/N2 mixed insulating gas recovery and separation",
      "Membrane separation technology separates SF6 and N2 efficiently",
      "Separated SF6 can be recovered to internal equipment or external cylinders for reuse",
      "Separated N2 can be discharged to the atmosphere after separation",
      "Oil-free compressor keeps separated gas clean and free from oil contamination",
      "Vacuum compressor supports deep recovery of residual gas",
      "PLC automatic control and touch screen operation make the process clear",
    ],
    specs: {
      Model: "RF-151M",
      Type: "SF6/N2 mixed gas recovery and separation unit",
      "Special application": "SF6/N2 mixed gas insulated electrical equipment",
      Gas: "SF6 / N2 mixed insulating gas",
      Function: "Mixed gas recovery / online separation / SF6 reuse",
      Compressor: "Oil-free compressor, 15 m3/h",
      "Vacuum pump": "64 m3/h",
      "Separation method": "Membrane separation technology",
      Operation: "Touch screen / button operation",
      Control: "PLC automatic control",
      "Power supply": "AC 380 V, 50 Hz",
      "Recovered gas": "SF6 recovered to internal equipment or external cylinder",
      "Separated gas": "N2 can be discharged to atmosphere after separation",
    },
  },
  {
    slug: "mobile-sf6-vacuum-pump-unit",
    article: "VP Series",
    name: "Mobile SF6 Vacuum Pump Unit",
    range: "SF6",
    group: "",
    application: "Vacuum evacuation",
    summary:
      "Mobile vacuum pump unit for evacuating SF6 gas compartments before filling and commissioning.",
    image: "/pic/mobile-sf6-vacuum-pump-unit.webp",
    sourceUrl: "https://www.sf6relations.com/mobile-sf6-vacuum-pump-unit/",
    badges: ["Vacuum", "Mobile", "Commissioning"],
    highlights: [
      "Mobile vacuum unit for SF6 gas compartment preparation",
      "Supports evacuation before refilling operations",
      "Built for site commissioning and maintenance teams",
    ],
    specs: {
      Function: "Vacuum evacuation",
      Mobility: "Mobile",
      Use: "Before SF6 filling",
      "Evacuation speed": "17 / 64 / 100 / 200 / 300 m3/h by model",
      "Final vacuum": "< 1 mbar",
      Models: "RFS17, RFS64, RFS100, RFS200, RFS300",
    },
  },
  {
    slug: "sf6-regeneration",
    article: "RF-300",
    name: "SF6 Regeneration System",
    range: "SF6",
    group: "SF6 Service carts",
    application: "Gas regeneration",
    summary:
      "Medium to large SF6 recovery and regeneration system with PLC control, purification, circulation purification, and refilling functions.",
    image: "/pic/sf6-regeneration-system.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-regeneration/",
    badges: ["Regeneration", "Reuse", "Purification"],
    highlights: [
      "PLC intelligent control with touch screen one-button operation",
      "Molecular sieve regeneration and refrigeration circulation purification",
      "Treated SF6 purity can reach 99.9% and meet GB12022-2014 new-gas standard",
      "Oil-free compressor and independent recovery/refilling pipelines reduce cross contamination",
      "Automatic negative-pressure deep recovery improves gas utilization",
      "Two refilling ports support direct filling and pressure-boosted filling",
      "Tank weighing sensor displays gas weight changes in real time",
    ],
    specs: {
      Model: "RF-300J",
      Type: "SF6 recovery and regeneration system",
      Gas: "SF6",
      Function: "Vacuum evacuation / recovery purification / circulation purification / refilling",
      Control: "PLC intelligent control with touch screen operation",
      "Vacuum compressor": "15 m3/h",
      "Vacuum pump": "64 m3/h",
      Dimensions: "2400 mm x 1400 mm x 1956 mm",
      Weight: "1800 kg",
      "Power supply": "380 V +/- 10%, 50/60 Hz",
      Power: "20 kW",
      "Storage tank": "320 L",
      "Tank working pressure": "3.7 MPa",
      "Final vacuum": "<= 10 Pa",
      "Recovery inlet pressure": "< 0.6 MPa",
      "Recovery speed": "150 kg/h max.",
      "Filling speed": "80 kg/h max.",
      "Refilling pressure": "< 3.5 MPa",
      "Annual leakage rate": "< 1%",
      Noise: "< 75 dB(A)",
      "Ambient temperature": "-10 C to +40 C",
      Humidity: "< 90% RH, non-condensing",
      "Dust filtration accuracy": "< 1 um",
      "Moisture after treatment": "<= 40 ppmv",
      "CF4 after treatment": "<= 0.01%",
      "Air content after treatment": "<= 0.03%",
      "Regenerated purity": ">= 99.9%",
      Standard: "GB12022-2014 new-gas standard",
      "Recovery mode": "Recover to purification tank first, or recover to external cylinder",
      "Refilling modes": "Direct pressure-difference filling or boosted filling",
      "System control": "PLC intelligent control and touch screen operation",
      "Purification system": "Molecular sieve regeneration filter and refrigeration circulation purification",
      "Pipeline design": "Independent recovery and refilling pipelines to reduce cross contamination",
      "Measurement system": "Storage tank weighing sensor for real-time gas weight display",
      "Refilling ports": "2 ports for direct filling and pressure-boosted filling",
    },
  },
  {
    slug: "rf391-mega-sf6-gas-handling",
    article: "RF-391",
    name: "RF391 Mega SF6 Gas Handling",
    range: "SF6",
    group: "SF6 Service carts",
    application: "High-capacity gas handling",
    summary:
      "Mega SF6 gas handling unit for 50 to 400 kg SF6 recovery, evacuation, refilling, and large GIS maintenance work.",
    image: "/pic/rf391-mega-sf6-gas-handling.webp",
    sourceUrl: "https://www.sf6relations.com/rf391-mega-sf6-gas-handling/",
    badges: ["High capacity", "Utility", "Mega handling"],
    highlights: [
      "Designed for 50 to 400 kg large-volume SF6 gas handling",
      "Up to 72 standard configuration combinations for complex field requirements",
      "Oil-free compressor and oil-free vacuum compressor keep SF6 gas clean",
      "Final recovery vacuum below 1 mbar and IEC 62271-4 compliant",
      "Gas booster system can fill a 40 L cylinder with liquid SF6 in about 5 minutes",
      "Built-in dehydration and impurity filter with molecular sieve regeneration",
      "Touch screen control and built-in SF6 gas cooling system improve automation",
    ],
    specs: {
      Model: "RF-391",
      Type: "Mega SF6 gas handling unit",
      Gas: "SF6",
      "Recommended gas quantity": "50 to 400 kg",
      "Application range": "110 kV to 500 kV GIS",
      "Model options": "Up to 72 standard configuration combinations",
      "Control modes": "One-button control (K) or touch screen control (T)",
      "Vacuum compressor options": "15 m3/h <= 5000 Pa; 20 m3/h <= 5 Pa; 40 m3/h <= 5 Pa",
      "Vacuum pump options": "64 / 100 / 200 / 300 m3/h, final vacuum <= 10 Pa",
      "Roots pump options": "251 / 505 m3/h, final vacuum <= 10 Pa",
      "Storage tank options": "No tank / 220 L / 300 L / 400 L / 500 L / 600 L",
      "Oil-free water-cooled compressor": "30 m3/h",
      "Output final pressure": "50 bar",
      "Oil-free booster": "5 m3/h for liquid SF6 filling",
      "Evacuation speed": "64 / 100 / 200 / 300 m3/h vacuum pump; 251 / 505 m3/h Roots pump",
      "Recovery final vacuum": "< 1 mbar",
      "Final vacuum": "< 10 Pa by vacuum pump",
      "Standard storage tank": "300 L with weighing function",
      "Dust filtration accuracy": "< 1 um",
      "Power supply": "AC 380 V, 50 Hz, three phase",
      Dimensions: "2030 mm x 1230 mm x 1930 mm",
      Weight: "1500 kg",
      "Standard vacuum compressor": "15 m3/h, final vacuum < 1 mbar",
      "Standard vacuum pump": "64 m3/h, final vacuum < 10 Pa",
      "Cooling system": "3P refrigeration system",
      "Filtering system": "Built-in dehydration and impurity filter with molecular sieve regeneration",
      "Cylinder filling": "About 5 minutes to fill a 40 L cylinder",
      Language: "Chinese / English touch screen operation",
      "Connection hose": "10 m DN20 steel braided hose with self-sealing couplings",
      "Cylinder hose": "3 m DN20 self-sealing coupling with China cylinder connector",
      "Power cable": "10 m",
      Color: "Orange",
    },
  },
  {
    slug: "sf6-gas-fittings",
    article: "RFCG",
    name: "SF6 Gas Fittings",
    range: "Accessories",
    group: "coupling",
    application: "Connection accessories",
    summary:
      "SF6 gas fittings, refilling couplings, and connection accessories for gas handling systems.",
    image: "/pic/sf6-gas-fittings.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-gas-fittings/",
    badges: ["Couplings", "Fittings", "Accessories"],
    highlights: [
      "Connection accessories for SF6 gas handling",
      "Suitable for refilling couplings and service interfaces",
      "Supports complete gas cart and switchgear maintenance setups",
    ],
    specs: {
      Type: "Fittings and couplings",
      Use: "Connection and refilling",
      Compatibility: "SF6 handling systems",
    },
  },
  {
    slug: "sf6-gas-density",
    article: "Density Monitor",
    name: "SF6 Gas Density Indicator Transmitter",
    range: "SF6",
    group: "SF6 Gas Density",
    application: "Density supervision",
    summary:
      "SF6 gas density indicator and transmitter for monitoring gas pressure and density conditions.",
    image: "/pic/sf6-gas-density-indicator-transmitter.webp",
    sourceUrl: "https://www.sf6relations.com/sf6-gas-density/",
    badges: ["Density", "Transmitter", "Monitoring"],
    highlights: [
      "Density supervision for SF6 gas insulated equipment",
      "Indicator and transmitter format for monitoring systems",
      "Supports operational visibility in switchgear assets",
    ],
    specs: {
      Parameter: "Gas density",
      Format: "Indicator / transmitter",
      Use: "Switchgear monitoring",
    },
  },
  {
    slug: "sf6-gas-system-for-gis-manufacturers",
    article: "GIS System",
    name: "SF6 Gas System for GIS Manufacturers",
    range: "SF6",
    group: "SF6 Gas System",
    application: "GIS manufacturing",
    summary:
      "SF6 gas system solutions for gas insulated switchgear manufacturers and production line applications.",
    image: "/pic/sf6-gas-system-for-gis-manufacturers.webp",
    sourceUrl:
      "https://www.sf6relations.com/sf6-gas-system-for-gis-manufacturers/",
    badges: ["GIS OEM", "Production", "System solution"],
    highlights: [
      "SF6 gas system for GIS manufacturing workflows",
      "Supports production, testing, filling, and recovery processes",
      "Designed for OEM and factory-scale gas management",
    ],
    specs: {
      Customer: "GIS manufacturers",
      Scope: "System solution",
      Workflow: "Production gas handling",
    },
  },
  {
    slug: "hydrogen",
    article: "H2 Portfolio",
    name: "Hydrogen Sensor Instrumentation and Equipment",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Hydrogen safety and quality",
    summary:
      "Hydrogen product line covering hydrogen sensors, leakage monitoring, gas quality analysis, and purification equipment.",
    image: "/pic/hydrogen-sensor-instrumentation-and-equipment.webp",
    sourceUrl: "https://www.sf6relations.com/hydrogen/",
    badges: ["Hydrogen", "H2 safety", "Instrumentation"],
    highlights: [
      "Hydrogen sensors and instruments for industrial gas applications",
      "Covers leakage monitoring, purity analysis, oxygen analysis, and purification",
      "Suitable for hydrogen-cooled generators, process gas systems, and safety monitoring",
    ],
    specs: {
      Gas: "Hydrogen",
      Scope: "Sensors / analyzers / systems",
      Scenario: "Safety and quality control",
    },
  },
  {
    slug: "hydrogen-analyzer",
    article: "RA701",
    name: "RA701 Portable Hydrogen Purity Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Hydrogen quality analysis",
    summary:
      "Portable hydrogen purity analyzer used for measuring purity, humidity, and oxygen content of hydrogen during normal operation.",
    image: "/pic/ra701-portable-hydrogen-purity-analyzer.webp",
    sourceUrl: "https://www.sf6relations.com/hydrogen-analyzer/",
    badges: ["Portable", "Purity", "Humidity", "Oxygen"],
    highlights: [
      "Measures hydrogen purity, humidity, and oxygen content",
      "Designed for normal operation checks and gas quality verification",
      "Portable format for site inspection and maintenance teams",
    ],
    specs: {
      Model: "RA701",
      Parameters: "Purity / humidity / oxygen",
      Format: "Portable analyzer",
    },
  },
  {
    slug: "rs301on-online-hydrogen-purity-analyzer",
    article: "RS301ON",
    name: "RS301ON Online Hydrogen Purity Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Online purity monitoring",
    summary:
      "Online hydrogen purity analyzer for continuous hydrogen gas quality monitoring in industrial operation.",
    image: "/pic/rs301on-online-hydrogen-purity-analyzer.webp",
    sourceUrl:
      "https://www.sf6relations.com/rs301on-online-hydrogen-purity-analyzer/",
    badges: ["Online", "Purity", "Continuous"],
    highlights: [
      "Continuous online hydrogen purity measurement",
      "Supports real-time gas quality supervision",
      "Useful for generator and industrial hydrogen systems",
    ],
    specs: {
      Model: "RS301ON",
      Parameter: "Hydrogen purity",
      Format: "Online analyzer",
    },
  },
  {
    slug: "rs301ex-hydrogen-quality-online-analyzer",
    article: "RS301EX",
    name: "RS301EX Hydrogen Quality Online Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Hydrogen quality monitoring",
    summary:
      "Online hydrogen quality analyzer for monitoring hydrogen gas condition in continuous industrial applications.",
    image: "/pic/rs301ex-hydrogen-quality-online-analyzer.webp",
    sourceUrl:
      "https://www.sf6relations.com/rs301ex-hydrogen-quality-online-analyzer/",
    badges: ["Online", "Quality", "Industrial"],
    highlights: [
      "Online supervision of hydrogen gas quality",
      "Designed for continuous industrial operation",
      "Supports gas safety and process stability monitoring",
    ],
    specs: {
      Model: "RS301EX",
      Parameter: "Hydrogen quality",
      Format: "Online analyzer",
    },
  },
  {
    slug: "ra1630-online-hydrogen-oxygen-analyzer",
    article: "RA1630",
    name: "RA1630 Online Hydrogen Oxygen Analyzer",
    range: "Hydrogen",
    group: "H2 Gas analyzers",
    application: "Hydrogen oxygen analysis",
    summary:
      "Online hydrogen oxygen analyzer for oxygen content monitoring in hydrogen-related gas systems.",
    image: "/pic/ra1630-online-hydrogen-oxygen-analyzer.webp",
    sourceUrl:
      "https://www.sf6relations.com/ra1630-online-hydrogen-oxygen-analyzer/",
    badges: ["Online", "Oxygen", "Hydrogen"],
    highlights: [
      "Online oxygen monitoring for hydrogen systems",
      "Supports safety supervision in hydrogen process environments",
      "Built for continuous industrial measurement workflows",
    ],
    specs: {
      Model: "RA1630",
      Parameter: "Oxygen in hydrogen",
      Format: "Online analyzer",
    },
  },
  {
    slug: "hydrogen-leakage-monitoring",
    article: "H2 Leakage System",
    name: "Hydrogen Leakage Monitoring",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Generator cooling safety",
    summary:
      "Hydrogen leakage monitoring solution for thermal power plants and hydrogen-cooled generator safety.",
    image: "/pic/hydrogen-leakage-monitoring.webp",
    sourceUrl: "https://www.sf6relations.com/hydrogen-leakage-monitoring/",
    badges: ["Leakage", "Generator", "Safety"],
    highlights: [
      "Hydrogen leakage monitoring for thermal power plant generator systems",
      "Supports safety supervision where hydrogen is used as cooling gas",
      "Combines fixed monitoring and portable detection use cases",
    ],
    specs: {
      Gas: "Hydrogen",
      Scenario: "Generator cooling",
      Function: "Leakage monitoring",
    },
  },
  {
    slug: "na1000d-multi-channel-hydrogen-leakage-monitoring-system",
    article: "NA1000D",
    name: "NA1000D Multi-channel Hydrogen Leakage Monitoring System",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Multi-point leakage monitoring",
    summary:
      "Multi-channel hydrogen leakage monitoring system for fixed multi-point safety monitoring in hydrogen facilities.",
    image: "/pic/na1000d-multi-channel-hydrogen-leakage-monitoring-system.webp",
    sourceUrl:
      "https://www.sf6relations.com/na1000d-multi-channel-hydrogen-leakage-monitoring-system/",
    badges: ["Multi-channel", "Fixed", "Safety"],
    highlights: [
      "Multi-channel fixed hydrogen leakage monitoring",
      "Designed for facility-wide safety supervision",
      "Suitable for hydrogen-cooled generator and industrial gas rooms",
    ],
    specs: {
      Model: "NA1000D",
      Type: "Multi-channel system",
      Function: "Leakage monitoring",
    },
  },
  {
    slug: "na1-portable-hydrogen-leak-detector",
    article: "NA1",
    name: "NA1 Portable Hydrogen Leak Detector",
    range: "Hydrogen",
    group: "H2 Leakage monitoring",
    application: "Portable leak inspection",
    summary:
      "Portable hydrogen leak detector for field inspection, maintenance checks, and hydrogen safety troubleshooting.",
    image: "/pic/na1-portable-hydrogen-leak-detector.webp",
    sourceUrl: "https://www.sf6relations.com/na1-portable-hydrogen-leak-detector/",
    badges: ["Portable", "Leak detector", "Maintenance"],
    highlights: [
      "Portable detection for hydrogen leakage inspection",
      "Useful for routine maintenance and emergency troubleshooting",
      "Complements fixed hydrogen monitoring systems",
    ],
    specs: {
      Model: "NA1",
      Type: "Portable detector",
      Function: "Hydrogen leak detection",
    },
  },
  {
    slug: "hydrogen-sensor",
    article: "H2 Sensors",
    name: "Hydrogen Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Sensor selection",
    summary:
      "Hydrogen sensor product line based on different physical or chemical principles for performance, cost, and scenario needs.",
    image: "/pic/hydrogen-sensor.webp",
    sourceUrl: "https://www.sf6relations.com/hydrogen-sensor/",
    badges: ["Sensor", "H2", "Instrumentation"],
    highlights: [
      "Hydrogen sensors based on multiple measurement principles",
      "Supports different performance, cost, and installation requirements",
      "Covers pipeline, automotive-grade, and thermal conductivity sensing",
    ],
    specs: {
      Gas: "Hydrogen",
      Type: "Sensor portfolio",
      Use: "Detection and measurement",
    },
  },
  {
    slug: "pps101-pipeline-type-palladium-alloy-hydrogen-sensor",
    article: "PPS101",
    name: "PPS101 Pipeline Type Palladium Alloy Hydrogen Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Pipeline hydrogen sensing",
    summary:
      "Pipeline type palladium alloy hydrogen sensor for hydrogen concentration sensing in pipeline applications.",
    image: "/pic/pps101-pipeline-type-palladium-alloy-hydrogen-sensor.webp",
    sourceUrl:
      "https://www.sf6relations.com/pps101-pipeline-type-palladium-alloy-hydrogen-sensor/",
    badges: ["Pipeline", "Palladium alloy", "Sensor"],
    highlights: [
      "Pipeline type hydrogen sensor construction",
      "Palladium alloy sensing route for hydrogen applications",
      "Suitable for process and pipeline-mounted measurement",
    ],
    specs: {
      Model: "PPS101",
      Principle: "Palladium alloy",
      Installation: "Pipeline type",
    },
  },
  {
    slug: "pdm200-automotive-hydrogen-concentration-sensor",
    article: "PDM200",
    name: "PDM200 Automotive Grade Hydrogen Concentration Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Hydrogen concentration sensing",
    summary:
      "Automotive-grade hydrogen concentration sensor for compact and reliable hydrogen detection applications.",
    image: "/pic/pdm200-automotive-grade-hydrogen-concentration-sensor.webp",
    sourceUrl:
      "https://www.sf6relations.com/pdm200-automotive-hydrogen-concentration-sensor/",
    badges: ["Automotive grade", "Concentration", "Sensor"],
    highlights: [
      "Automotive-grade hydrogen concentration sensing",
      "Compact sensor for hydrogen safety applications",
      "Useful for equipment-level hydrogen detection integration",
    ],
    specs: {
      Model: "PDM200",
      Parameter: "Hydrogen concentration",
      Grade: "Automotive",
    },
  },
  {
    slug: "tcs101-thermal-conductivity-hydrogen-purity-sensor",
    article: "TCS101",
    name: "TCS101 Thermal Conductivity Hydrogen Purity Sensor",
    range: "Hydrogen",
    group: "H2 Sensors",
    application: "Hydrogen purity sensing",
    summary:
      "Thermal conductivity hydrogen purity sensor for hydrogen purity measurement and equipment integration.",
    image: "/pic/tcs101-thermal-conductivity-hydrogen-purity-sensor.webp",
    sourceUrl:
      "https://www.sf6relations.com/tcs101-thermal-conductivity-hydrogen-purity-sensor/",
    badges: ["Thermal conductivity", "Purity", "Sensor"],
    highlights: [
      "Thermal conductivity route for hydrogen purity sensing",
      "Designed for hydrogen purity measurement applications",
      "Useful as an embedded sensing component in analyzer systems",
    ],
    specs: {
      Model: "TCS101",
      Principle: "Thermal conductivity",
      Parameter: "Hydrogen purity",
    },
  },
  {
    slug: "rlhj68-hydrogen-purification-device",
    article: "RLHJ68",
    name: "RLHJ68 Hydrogen Purification Device",
    range: "Hydrogen",
    group: "H2 Gas purification",
    application: "Hydrogen purification",
    summary:
      "Hydrogen purification device for improving hydrogen gas quality in industrial hydrogen applications.",
    image: "/pic/rlhj68-hydrogen-purification-device.webp",
    sourceUrl: "https://www.sf6relations.com/rlhj68-hydrogen-purification-device/",
    badges: ["Purification", "Hydrogen", "Gas quality"],
    highlights: [
      "Hydrogen purification for gas quality improvement",
      "Supports industrial hydrogen quality management",
      "Complements hydrogen analysis and monitoring product lines",
    ],
    specs: {
      Model: "RLHJ68",
      Function: "Hydrogen purification",
      Goal: "Gas quality improvement",
    },
  },
];

export function getProduct(slug: string) {
  return products.find((product) => product.slug === slug);
}
